SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE = 0.9 # seconds
ASTEROID_MAX_RADIUS = 60
ASTEROID_MEDIUM_RADIUS = 40

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Normal shooting
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
